"""crear_modulo_usuarios

Revision ID: 346ae1b3d9a2
Revises: 
Create Date: 2026-05-19 11:40:10.789797

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '346ae1b3d9a2'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usuarios',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('primer_nombre', sa.String(length=50), nullable=False),
    sa.Column('segundo_nombre', sa.String(length=50), nullable=True),
    sa.Column('primer_apellido', sa.String(length=50), nullable=False),
    sa.Column('segundo_apellido', sa.String(length=50), nullable=True),
    sa.Column('cedula', sa.String(length=20), nullable=False),
    sa.Column('correo', sa.String(length=150), nullable=False),
    sa.Column('hash_contrasena', sa.String(), nullable=False),
    sa.Column('telefono', sa.String(length=20), nullable=True),
    sa.Column('rol', sa.String(length=20), nullable=False),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.Column('fecha_registro', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cedula'),
    sa.UniqueConstraint('correo')
    )
    op.create_table('direcciones',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('usuario_id', sa.UUID(), nullable=False),
    sa.Column('direccion', sa.String(length=200), nullable=False),
    sa.Column('departamento', sa.String(length=100), nullable=False),
    sa.Column('ciudad', sa.String(length=100), nullable=False),
    sa.Column('principal', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('historial_correos',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('usuario_id', sa.UUID(), nullable=False),
    sa.Column('correo_anterior', sa.String(length=150), nullable=False),
    sa.Column('fecha_cambio', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('historial_correos')
    op.drop_table('direcciones')
    op.drop_table('usuarios')
    # ### end Alembic commands ###
